version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
  app:
    image: golang:1.23
    container_name: inventario_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mongo
    command:
      [
        "go",
        "run",
        "cmd/api/application.go",
        "cmd/api/main.go",
        "cmd/api/routes.go",
      ]
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - DATABASE=inventario
      - COLLECTION_INGREDIENTE=ingrediente
      - COLLECTION_RECETA=receta
